### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by qijiale** [stoyanov-st/AlphaMinerImplementation#2]
Hi.
I am trying to compiled code with python3.4. After the compilation  I am getting following error:
"NameError: name 'unicode' is not defined"
Can you tell me how to solve it?

**Comment by stoyanov-st** [comment]
In python 3 
`unicode` is renamed to `std`

[](https://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3)

**Comment by qijiale** [comment]
Thanks ！




| |
刘杰
邮箱：liujie_ran@163.com
|

签名由 网易邮箱大师 定制

On 03/27/2018 18:20, S.Stoyanov wrote:

In python 3
unicode is renamed to std

[https://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3]
